name: EAS Update Main
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:ci
      - name: Build on EAS
        run: eas update --non-interactive --branch main --message ${{ github.event.head_commit.message }}
